### ISSUE TITLE
Calling an asynchronous function without callback is deprecated

### ISSUE THREAD

**Issue by guyellis** [kesla/sort-json#10] opened 2017-04-19 03:55 UTC
On Node 7.9.0 (and probably others) the following warning during usage:

```
(node:658) DeprecationWarning: Calling an asynchronous function
  without callback is deprecated.
```

**Comment by dodekeract** [comment] 2017-04-19 11:57
Duplicate of #9.

**Closed** 2017-09-29 09:32 UTC
